### ISSUE TITLE
Add Davis Instruments to Weather Station

### ISSUE THREAD

**Issue by SolarSciencePup** [flipperdevices/flipperzero-good-faps#58]

**Comment by skotopes** [comment]
Pleas provide:
- Exact model and vendor name
- Raw recordings of it's signal at different temperatures

**Comment by Skorpionm** [comment]
photo of the remote module, photo of the receiving module, raw recordings of transmissions at increasing temperatures (when only 1 decimal place changes >4 pieces, records with changes in full degrees at positive and negative temperatures >10 pieces) with the obligatory photo that shows the receiving module.  recordings and photos of the receiving module, when setting up an external module on different channels, if more than 1 module is supported.  raw recording of readings when removing and inserting batteries, at the same temperature

**Comment by SolarSciencePup** [comment]
Removing and reinserting batteries and receiving module I can't get

**Comment by SolarSciencePup** [comment]
Do have FCC ID though: IR2DWW6357

**Comment by SolarSciencePup** [comment]
> Pleas provide:
> - Exact model and vendor name
> - Raw recordings of it's signal at different temperatures

Vantage Vue Wireless Integrated Sensor Suite Weather Station - SKU 6357, 6357M

By Davis Instruments

**Comment by skotopes** [comment]
FCC ID says that this device uses FSK in a range between 902 - 927 MHz with channelization scheme.
It sounds slightly more complex than common weather stations and requires different architecture this sensor.

At this point we are not planning to reverse engineer it, but maybe someone from community will do.
Also because of the radio protocol complexity the best option will be to move this sensor to separate application.
